# Declaracion de variables
p = float()
a = float()
b = float()
bb = float()
h = float()
l1 = float()
l2 = float()
l3 = float()
l4 = float()
print("AREA DEL TRAPECIO")
print("BASE MAYOR  : ", end="")
b = float(input())
print("BASE MENOR  : ", end="")
bb = float(input())
print("ALTURA      : ", end="")
h = float(input())
a = ((b*bb)*h)/2
print("AREA : ",a,"cm2")
print("")
print("PERIMETRO DEL TRAPECIO")
print("LASO 01 : ", end="")
l1 = float(input())
print("LASO 02 : ", end="")
l2 = float(input())
print("LASO 03 : ", end="")
l3 = float(input())
print("LASO 04 : ", end="")
l4 = float(input())
p = l1+l2+l3+l4
print("PERIMETRO : ",p,"cm")

